version: "3"
services:
  web:
    build: "."
    ports:
      - 127.0.0.1:${PORT}:80
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
